"""empty message

Revision ID: 2092570df74e
Revises: 
Create Date: 2020-10-31 22:48:04.791730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2092570df74e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimentacoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('categoria', sa.Enum('alimentacao', 'educacao', 'lazer', 'saude', 'transporte'), nullable=False),
    sa.Column('tipo', sa.Enum('pagar', 'receber'), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimentacoes')
    # ### end Alembic commands ###
